CREATE DATABASE TESTE
GO
USE TESTE
GO
CREATE TABLE TESTE(
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    NOME VARCHAR(MAX),
    IDADE VARCHAR(MAX)
)

GO

DECLARE @NOME VARCHAR(MAX)
DECLARE @IDADE VARCHAR(MAX)
DECLARE CURSOR1 CURSOR FOR SELECT NOME, IDADE FROM TESTE
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME, @IDADE
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @NOME
    PRINT @IDADE
    FETCH NEXT FROM CURSOR1 INTO @NOME,@IDADE
END

CLOSE CURSOR1
DEALLOCATE CURSOR1

SELECT * FROM TESTE