CREATE TABLE TAB_CHECK(
ID INT NOT NULL,
NOME VARCHAR(MAX) NULL,
IDADE INT NULL,
CIDADE VARCHAR(MAX) NULL,
CONSTRAINT CHK_PESSOA CHECK (IDADE >=18)
)

INSERT INTO TAB_CHECK(ID,NOME,IDADE,CIDADE) VALUES (2,'JOÃO',18,'RIO DE JANEIRO')

SELECT * FROM TAB_CHECK
