CREATE DATABASE AULA1609

GO

USE AULA1609

GO

CREATE TABLE TESTE(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOME VARCHAR(MAX)
)

GO

DECLARE @NOME VARCHAR(MAX) /*VARIAVEL PARA CURSOR*/
DECLARE CURSOR1 CURSOR FOR /*CRIA CURSOR PARA O SELECT DE BAIXO*/
SELECT NOME FROM TESTE
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 /*POSICIONA CURSOR NA PRIMEIRA POSIÇÃO*/
INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END

CLOSE CURSOR1
DEALLOCATE CURSOR1

INSERT INTO TESTE(NOME) VALUES ('ALEXANDRE')
INSERT INTO TESTE(NOME) VALUES ('WILIAN')
INSERT INTO TESTE(NOME) VALUES ('NIKITIN')
INSERT INTO TESTE(NOME) VALUES ('BRUNO')
INSERT INTO TESTE(NOME) VALUES ('MURILO')
INSERT INTO TESTE(NOME) VALUES ('LUIS')